http-interface-clients:
  class-customizer-client:
    url: http://localhost:${wiremock.port}
    customizer-class: art.picsell.starter.applicationTest.customizer.classname.customizer.ClassHeaderCustomizer
